### ISSUE TITLE
Bump VirgilSDK to support Apple Silicon

### ISSUE THREAD

**Issue by alistra** [ClaySolutions/ClaySDK#11]
Can you please bump VirgilSDK to a newer version, as currently because of VirgilCrypto our app can't build on the arm64 simulator.

<img width="771" alt="Screenshot 2021-11-24 at 17 09 54" src="https://user-images.githubusercontent.com/233144/143274183-462330d5-0dbd-4cab-8d79-eb8b4a9961ed.png">

According to their release notes, they support Apple Silicon now in version 8

https://github.com/VirgilSecurity/virgil-sdk-x/releases/tag/8.0.0

Offending line in podspec:

```
  s.dependency 'VirgilSDK', '7.2.1'
```
CC @mlepicki

**Comment by jakov-clay** [comment]
Hi @alistra, indeed Virgil SDK from latest version do support arm64 simulator architecture for Apple Silicon.
Problem is that currently our other library (JustIN SDK) still do not support this architecture, so even if we move to new version of Virgil SDK you will still need to exclude arm64.
When we have everything ready and in place we will publish new version that supports this.
For now I suggest to keep that Excluded Architectures option in Xcode project settings.

**Comment by alistra** [comment]
@jakov-clay thanks for the quick response. I assume JustIN SDK is compiled into your artifact? Because I don't see any references to it.

Please prioritize this, as this is the only blocking library for us to adopt arm64 in our app :)

**Comment by alistra** [comment]
@jakov-clay is there any timeline for this?

**Comment by jakov-clay** [comment]
@alistra today :) funny that you ask because I was just able to build version that works. I have to do a few more tests to confirm everything is ok.

**Comment by alistra** [comment]
I'm very excited - The issue we are facing is that some of our developers (including me) have M1, and because this library doesn't support arm64 simulator, the app actually shows as Kind = Intel in Activity Monitor and goes through Rosetta transpilation on every code change, which can take about 10 seconds of waiting for launch :)

**Comment by jakov-clay** [comment]
@alistra new version with arm64 simulator support is released: https://github.com/ClaySolutions/ClaySDK/releases/tag/1.10.0
You also need to update JustINSDK manually. You can find that in privately shared Drive or Dropbox folder .

**Comment by alistra** [comment]
We just tested it and in fact after bumping the `ClaySDK` pod and updating the `JustINSDK` it now builds natively on M1 

🎉
