### ISSUE TITLE
Symbol not found: _OBJC_CLASS_$_SSJustinBle

### ISSUE THREAD

**Issue by sbezhuk** [ClaySolutions/ClaySDK#17]
Hi, I'm trying to implement a plugin for Flutter. I was able to connect successfully the `SaltoJustINMobileSDK` for the Android module, however, for the iOS module I get the following error.

```
dyld[67622]: Symbol not found: _OBJC_CLASS_$_SSJustinBle
  Referenced from: <E664A44A-6F1B-3A19-8AA0-ADF47A297312> /private/var/containers/Bundle/Application/8454868B-1D54-43C9-8CDB-B9CD73D39E1E/Runner.app/Frameworks/ClaySDK.framework/ClaySDK
  Expected in:     <E1C3961D-B8AF-38A7-9710-396B8B9D4D8B> /private/var/containers/Bundle/Application/8454868B-1D54-43C9-8CDB-B9CD73D39E1E/Runner.app/Frameworks/SaltoJustINMobileSDK.framework/SaltoJustINMobileSDK
```

Maybe someone has faced a similar problem and can help?

**Comment by jakov-clay** [comment]
Hey @fox-avokadik, we moved our repo to gitlab. You can find there latest version there, please contact support.
PS in build settings of the target you can check if you have under Framework Search Paths -> `$(inherited)`

**Comment by jakov-clay** [comment]
As I said you need to contact support, they will give you access to new version of ClaySDK (you need access tokens to install it).
If you are using SaltoKS APIs then you need to use ClaySDK, it will not work if you only use SaltoJustINMobileSDK

**Comment by fox-avokadik** [comment]
@jakov-clay I understand, then I think further discussion is not appropriate, because first me should update to ClaySDK to v2. Thanks for the advice
