### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler

### ISSUE THREAD

**Issue by DP2018-a** [ClaySolutions/ClaySDK#2]
Hey,

I'm using Xcode 11.5 and I've updated the latest version of SDK still I'm getting the following error:

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler

P.S: I did this so many times in the past and once I update the SDK it worked well with updated version Xcode but this time it's giving me this error.

**Comment by jakov-clay** [comment]
Latest version (1.7.3) should be compiled with Swift 5.2 compiler
Check Podfile.lock and look for version of ClaySDK
if you are using pods like this:
`pod 'ClaySDK', '~> 1.7'`
try running
`pod install --repo-update`
to fetch latest version of pod

**Comment by DP2018-a** [comment]
Thanks. I've updated the SALTOJustInMobileSDK and pods and it worked.
