### ISSUE TITLE
Unable to install ClaySDK with Xcode 12

### ISSUE THREAD

**Issue by franconob** [ClaySolutions/ClaySDK#3]
Today I have updated my Xcode to v12. This latest version ships with Swift 5.3, so using the `pod` to install the sdk throws an error now when my project is compiled. I'm trying to use `carthage` instead, but I'm getting the following error:
```
# carthage update --platform iOS
*** Downloading ClaySDK.framework binary at "1.8.0"

***  Skipped installing ClaySDK.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53) and the local version is 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)."
    Falling back to building from the source
*** Skipped building ClaySDK due to the error:
Dependency "ClaySDK" has no shared framework schemes for any of the platforms: iOS
```

My `Cartfile` contents:
`github "ClaySolutions/ClaySDK" "1.8.0"`

Thanks in advance

**Comment by lgenzelis** [comment]
Same here, XCode v12 does not seem to work  with the SDK ☹️

**Comment by ndlonghi** [comment]
Yes, same happening here. Help would be really useful.

**Comment by jakov-clay** [comment]
New version with Swift 5.3 support will be available early next week

**Comment by franconob** [comment]
Good news, thanks!

**Comment by jakov-clay** [comment]
Guys I'm reopening this issue for visibility. This part is almost automated process but at this point we have some problems with dependencies so it might take some time before we release it.
Will keep you informed.

**Comment by jakov-clay** [comment]
Carthage build is there but CocoaPods CDN is down so I can't push podspec until that is resolved

**Comment by krudos** [comment]
you can temporary add this on the beggining of your podfile to make cocoapods work
`source 'https://cocoapods-cdn.netlify.app/'`

**Comment by jakov-clay** [comment]
Since I was not able to push podspec to trunk that won't be enough.
Follow this comment to fix your pod install https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-696481185
To install latest version of ClaySDK use it like this:
`pod 'ClaySDK', :git => 'https://github.com/ClaySolutions/ClaySDK.git'`

**Comment by jakov-clay** [comment]
New version of ClaySDK is now available and via CocoaPods
`pod 'ClaySDK', '1.8.1'`
or run `pod update`

**Comment by franconob** [comment]
Awesome, thanks for the hard work!

**Comment by mlepicki** [comment]
For anyone having an issue with running app with ClaySDK 1.8.1 on simulator: I had to configure excludes in project settings & Podfile to make it work. Here's post on SO where I have found that solution: https://stackoverflow.com/a/63955114/1267592

**Comment by lgenzelis** [comment]
Thanks for taking care of this! :)
