### ISSUE TITLE
Invalid MKey signature

### ISSUE THREAD

**Issue by burla69** [ClaySolutions/ClaySDK#5]
Hello. When i use "accept" api key i can open all my doors.
When i want to use "develop" or "production" api can I always get an error: "Invalid MKey signature".
How can i solve this?

```
let clay = ClaySDK(installationUID: "36bffba2-00f6-4bf7-8f83-c1a8543*****", apiKey: "MFkwEwYHKoZIzj0CAQYIK*****", delegate: self)
        
        let publicKey = clay.getPublicKey()

        accountService.load(service: .mobileKey(publicKey: publicKey), decodeType: String.self) { (result) in
            switch result {
            case .success(let code):
                print(code)
                clay.openDoor(with: code, delegate: self)
            case .failure(let error):
                print(error)
            }
        }
```

**Comment by jakov-clay** [comment]
You are probably using always the same mkey activated on one of the environments and then it doesn't work on other. When switching environment you need to activate mkey via API for that environment.

**Comment by burla69** [comment]
Every time i use new mkey. But have Invalid MKey signature error

**Comment by burla69** [comment]
Maybe you have some sample example projects where i can check implementation

**Comment by jakov-clay** [comment]
Hmmm, then maybe you use wrong api public key. Be sure that you are using correct api public key.
Mentioned endpoint is only to fetch mkey for device. Before that you need to execute PUT request to update certificate.

**Comment by jakov-clay** [comment]
I do not have example project. Did you get document which describes mobile key activation?

**Comment by burla69** [comment]
> I do not have example project. Did you get document which describes mobile key activation?

Yes. I have documents on dropbox. And i use right api key. 
+ we update certificates every time when i want to open lock.

But it works only when i put ACCEPT api key. With this api key i can open all my locks

**Comment by jakov-clay** [comment]
It should work then. Maybe you missed something else. Are you sure you are also switching API url for each environment?

**Comment by burla69** [comment]
ohhhhh, i seeeeee. Problem in url...
we use https://clp-**accept**-user.my-clay.com/v1.1/me/devices/{id}/mkey
Sorry. Will check again

**Comment by burla69** [comment]
Thank you!)

**Comment by jakov-clay** [comment]
You'r welcome! 👍
