### ISSUE TITLE
ClaySDK not working with Xcode 12.2

### ISSUE THREAD

**Issue by jakov-clay** [ClaySolutions/ClaySDK#6]
Clay SDK not working with Xcode 12.2

Failed to build module 'ClaySDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

![Screenshot 2020-11-16 at 13 14 22](https://user-images.githubusercontent.com/56873230/99251467-ae5dc980-280d-11eb-93fc-529ff1c13ceb.png)

**Comment by jakov-clay** [comment]
We are working on solving this issue, new version of SDK will be released during this week. As workaround at the moment I can only suggest downloading Xcode 12.1 https://developer.apple.com/download/more/?q=xcode

**Comment by jakov-clay** [comment]
ClaySDK 1.8.2 was released which fixes this issue.

**Comment by JippeJoosten** [comment]
Thanks for the updates!

**Comment by JippeJoosten** [comment]
Is there a way to prevent this from happening with every Swift release? I do not have this issue with other frameworks/SDK's

**Comment by jakov-clay** [comment]
It's is a bit different with open and close source frameworks, but it should be possible. We have it in the plan after moving SDK to .xcframework format

**Comment by burla69** [comment]
can`t update pod to 1.8.2
This version works with cocoapods?

**Comment by jakov-clay** [comment]
@burla69 Yes, ClaySDK 1.8.2 should work with cocoapods. Do you have problem?
Maybe demo app would help? https://github.com/ClaySolutions/ClaySDKDemo

**Comment by burla69** [comment]
It works after pod install --repo-update
So now all good)
