### ISSUE TITLE
dyld: Library not loaded: @rpath/SaltoJustINMobileSDK.framework/SaltoJustINMobileSDK

### ISSUE THREAD

**Issue by ShashiTiwari07** [ClaySolutions/ClaySDK#7]
After following all the instruction from you team and also as detailed on Git, please find the issue below receiving on real device - 

dyld: Library not loaded: @rpath/SaltoJustINMobileSDK.framework/SaltoJustINMobileSDK
  Referenced from: /private/var/containers/Bundle/Application/977F85B1-23BD-4A4F-9EC9-683810C3774E/Test.app/Test
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib

**Comment by jakov-clay** [comment]
Did you include SaltoJustINMobileSDK.xcframework from dropbox folder? That framework is private so it could not be published here.

**Comment by ShashiTiwari07** [comment]
Yes included SaltoJustINMobileSDK.xcframework along with other shared framework from dropbox.

**Comment by jakov-clay** [comment]
@ShashiTiwari07 Ok! It should be maybe only SaltoJustIN because other ones (Virgil libraries) are pulled via CocoaPods as dependencies of ClaySDK
We can close this issue?

**Comment by ShashiTiwari07** [comment]
What is the solution to solve this problem? Please share. Once Issue will be resolved I will close this issue.

**Comment by jakov-clay** [comment]
so including SaltoJustIN directly to your project (in general tab) did not solve issue?

**Comment by ShashiTiwari07** [comment]
No getting the same issue. I tried multiple times by adding ony SDk while running on phone and adding SaltoJustINMobileSDK.xcframework as well but getting the same issue.

**Comment by jakov-clay** [comment]
![Screenshot 2020-11-18 at 10 54 00](https://user-images.githubusercontent.com/56873230/99514951-9eb8bf00-298c-11eb-919d-60eb9e97fb30.png)
here you can see how I included it in my project.

If that is not the issue I'm really not sure what else could be problem

**Comment by ShashiTiwari07** [comment]
Above was the issue, Please mention the same in you README file.
